// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYvQB53CzdNlw8v6nL_1kzTn1jHwdpARU',
    appId: '1:211636480916:web:29d04f4d7b51ab05783d81',
    messagingSenderId: '211636480916',
    projectId: 'fooddelivery-52168',
    authDomain: 'fooddelivery-52168.firebaseapp.com',
    storageBucket: 'fooddelivery-52168.firebasestorage.app',
    measurementId: 'G-J8P8M6MFPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNH-jCcsxR8pAKroMekr1E1laImUuf1gY',
    appId: '1:211636480916:android:a2d922fac55151a9783d81',
    messagingSenderId: '211636480916',
    projectId: 'fooddelivery-52168',
    storageBucket: 'fooddelivery-52168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKclDF-fH4876h2bS140Gorn-KTJ-NXBc',
    appId: '1:211636480916:ios:2b49b6ddaab137ad783d81',
    messagingSenderId: '211636480916',
    projectId: 'fooddelivery-52168',
    storageBucket: 'fooddelivery-52168.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKclDF-fH4876h2bS140Gorn-KTJ-NXBc',
    appId: '1:211636480916:ios:2b49b6ddaab137ad783d81',
    messagingSenderId: '211636480916',
    projectId: 'fooddelivery-52168',
    storageBucket: 'fooddelivery-52168.firebasestorage.app',
    iosBundleId: 'com.example.fooddelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYvQB53CzdNlw8v6nL_1kzTn1jHwdpARU',
    appId: '1:211636480916:web:50fce921e6c10260783d81',
    messagingSenderId: '211636480916',
    projectId: 'fooddelivery-52168',
    authDomain: 'fooddelivery-52168.firebaseapp.com',
    storageBucket: 'fooddelivery-52168.firebasestorage.app',
    measurementId: 'G-79E51CD8WD',
  );
}
